import type { Metadata } from "next";
import { Montserrat_Alternates } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inter = Montserrat_Alternates({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  );
}
